control_dt: 0.02

num_actions: 21

leg_joint2motor_idx: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

kps: [
    5., 5., # head
    20.0, 20.0, 20.0, 20.0, 10.0, 10.0, 10.0, # 7 dof left arm
    20.0, 20.0, 20.0, 20.0, 10.0, 10.0, 10.0, # 7 dof right arm
    200.0, # waist
    200, 200, 200, 250, 50, 50, # leg
    200, 200, 200, 250, 50, 50, # leg
    ]

kds: [
    0.1, 0.1, # head
    0.5, 0.5, 0.5, 0.5, 0.2, 0.2, 0.2, # 7 dof left arm
    0.5, 0.5, 0.5, 0.5, 0.2, 0.2, 0.2, # 7 dof right arm
    5.0, # waist
    5.0, 5.0, 5.0, 5.0, 3.0, 3.0, # leg
    5.0, 5.0, 5.0, 5.0, 3.0, 3.0, # leg
  ]

default_angles: [  
    0.0,  0.0, # head
    0.25, -1.4, 0.0, -0.5, 0.0, 0.0, 0.0, # left arm
    0.25, 1.4, 0.0, 0.5, 0.0, 0.0, 0.0, # right arm
    0.0, # waist
    -0.1, 0.0, 0.0, 0.2, -0.1, 0.0, # left leg
    -0.1, 0.0, 0.0, 0.2, -0.1, 0.0, # right leg
        ]

stand_angles: [
    0.0,  0.0, # head
    0.25, -1.4, 0.0, -0.5, 0.0, 0.0, 0.0, # left arm
    0.25, 1.4, 0.0, 0.5, 0.0, 0.0, 0.0, # right arm
    0.0, # waist
    -0.1, 0.0, 0.0, 0.2, -0.1, 0.0, # left leg
    -0.1, 0.0, 0.0, 0.2, -0.1, 0.0, # right leg
    ]

ang_vel_scale: 0.25
dof_pos_scale: 1.0
dof_vel_scale: 0.05
action_scale: 0.1 # full is 0.5

